In [1]:
import pandas as pd
from pathlib import Path

ROOT = Path.cwd().parent
DATAPATH = ROOT / "pima_api" / "data"

In [2]:
pima_df = pd.read_csv(DATAPATH.joinpath("pima.csv"))
pima_df.sample(4)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
765,5,121,72,23,112,26.2,0.245,30,0
215,12,151,70,40,271,41.8,0.742,38,1
137,0,93,60,25,92,28.7,0.532,22,0
731,8,120,86,0,0,28.4,0.259,22,1

In [6]:
def preprocess_dataset(datapath: Path | str) -> pd.DataFrame:
    df = pd.read_csv(datapath)
    eq_zero_series = df.eq(0).any().drop(labels=["Pregnancies", "Outcome"])
    mask = eq_zero_series.tolist()
    cols = eq_zero_series[mask].index
    df[cols] = df[cols].apply(lambda col_: col_.replace(0, col_.median()))

    return df

pima_df_prep = preprocess_dataset(DATAPATH.joinpath("pima.csv"))
pima_df_prep

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,30.5,33.6,0.627,50,1
1,1,85,66,29,30.5,26.6,0.351,31,0
2,8,183,64,23,30.5,23.3,0.672,32,1
3,1,89,66,23,94.0,28.1,0.167,21,0
4,0,137,40,35,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180.0,32.9,0.171,63,0
764,2,122,70,27,30.5,36.8,0.340,27,0
765,5,121,72,23,112.0,26.2,0.245,30,0
766,1,126,60,23,30.5,30.1,0.349,47,1
767,1,93,70,31,30.5,30.4,0.315,23,0